version: "3.3"
services:

  proxy:


  pgadmin:



  backend:

    environment:
      - PORT=8888


networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false
