"""
resource section added

Revision ID: 2d188d7adcf4
Revises: 
Create Date: 2023-10-11 07:29:02.957474+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic
revision: str = "2d188d7adcf4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_specification",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("href", sa.String(length=255), nullable=True),
        sa.Column("default_quantity", sa.Integer(), nullable=True),
        sa.Column("maximum_quantity", sa.Integer(), nullable=True),
        sa.Column("minimum_quantity", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("relationship_type", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resource_specification_id"),
        "resource_specification",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_resource_specification_id"), table_name="resource_specification"
    )
    op.drop_table("resource_specification")
    # ### end Alembic commands ###
