"""
reservation item table added

Revision ID: d9f0c8620990
Revises: e5976acba19e
Create Date: 2023-10-08 13:30:49.244813+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic
revision: str = "d9f0c8620990"
down_revision: str | None = "e5976acba19e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservation_item",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.String(length=255), nullable=True),
        sa.Column("sub_reservation_state", sa.String(length=255), nullable=True),
        sa.Column("applied_capacity_amount", sa.String(length=255), nullable=True),
        sa.Column("base_type", sa.String(length=255), nullable=True),
        sa.Column("schema_location", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("reservation_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_index(
        op.f("ix_reservation_item_id"), "reservation_item", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reservation_item_id"), table_name="reservation_item")
    op.drop_table("reservation_item")
    # ### end Alembic commands ###
