"""
Initial schema

Revision ID: 5abbe0660cf4
Revises: 
Create Date: 2023-10-05 11:41:36.451056+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic
revision: str = "5abbe0660cf4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservation",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("href", sa.String(length=255), nullable=True),
        sa.Column("base_type", sa.String(length=255), nullable=True),
        sa.Column("schema_location", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("reservation_state", sa.String(length=255), nullable=True),
        sa.Column(
            "valid_for", sa.Date(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reservation_id"), "reservation", ["id"], unique=False)
    op.create_table(
        "product_offering_ref",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("href", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("referred_type", sa.String(length=255), nullable=False),
        sa.Column("reservation_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_index(
        op.f("ix_product_offering_ref_id"), "product_offering_ref", ["id"], unique=False
    )
    op.create_table(
        "related_party_ref",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("referred_type", sa.String(length=255), nullable=True),
        sa.Column("href", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column("reservation_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_index(
        op.f("ix_related_party_ref_id"), "related_party_ref", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_related_party_ref_id"), table_name="related_party_ref")
    op.drop_table("related_party_ref")
    op.drop_index(op.f("ix_product_offering_ref_id"), table_name="product_offering_ref")
    op.drop_table("product_offering_ref")
    op.drop_index(op.f("ix_reservation_id"), table_name="reservation")
    op.drop_table("reservation")
    # ### end Alembic commands ###
