"""Initials

Revision ID: d8de033ca61c
Revises: 
Create Date: 2023-10-05 10:36:19.197436+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# Revision identifiers, used by Alembic
revision: str = "d8de033ca61c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservation",
        sa.Column("product_offering", sa.String(length=255), nullable=False),
    )
    op.alter_column(
        "reservation",
        "valid_for",
        existing_type=mysql.DATETIME(),
        type_=sa.Date(),
        existing_nullable=False,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.drop_column("reservation", "related_party")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservation",
        sa.Column("related_party", mysql.VARCHAR(length=255), nullable=False),
    )
    op.alter_column(
        "reservation",
        "valid_for",
        existing_type=sa.Date(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.drop_column("reservation", "product_offering")
    # ### end Alembic commands ###
