"""
resource pool table added

Revision ID: d3cc1dbb8015
Revises: 071670c52022
Create Date: 2023-10-09 15:00:06.861541+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# Revision identifiers, used by Alembic
revision: str = "d3cc1dbb8015"
down_revision: str | None = "071670c52022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_pool",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("href", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("related_party", sa.String(length=255), nullable=False),
        sa.Column("resource_collection", sa.String(length=255), nullable=False),
        sa.Column("base_type", sa.String(length=255), nullable=False),
        sa.Column("schema_location", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column("resource_pool_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_pool_id"],
            ["resource_pool.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_pool_id"),
    )
    op.create_index(op.f("ix_resource_pool_id"), "resource_pool", ["id"], unique=False)
    op.alter_column(
        "reservation_item",
        "quantity",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reservation_item",
        "quantity",
        existing_type=sa.Integer(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_resource_pool_id"), table_name="resource_pool")
    op.drop_table("resource_pool")
    # ### end Alembic commands ###
