"""
Add Requested period table

Revision ID: e5976acba19e
Revises: a80704e68b25
Create Date: 2023-10-06 10:27:18.211394+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic
revision: str = "e5976acba19e"
down_revision: str | None = "a80704e68b25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requested_period",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("base_type", sa.String(length=255), nullable=False),
        sa.Column("schema_location", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column("days_of_week", sa.String(length=255), nullable=False),
        sa.Column("from_to_date_time", sa.String(length=255), nullable=False),
        sa.Column("range_interval", sa.String(length=255), nullable=False),
        sa.Column(
            "valid_for", sa.Date(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("reservation_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_index(
        op.f("ix_requested_period_id"), "requested_period", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_requested_period_id"), table_name="requested_period")
    op.drop_table("requested_period")
    # ### end Alembic commands ###
