"""
Add channel reference table

Revision ID: a80704e68b25
Revises: 5abbe0660cf4
Create Date: 2023-10-05 15:28:01.536264+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic
revision: str = "a80704e68b25"
down_revision: str | None = "5abbe0660cf4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_ref",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("href", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("referred_type", sa.String(length=255), nullable=False),
        sa.Column("reservation_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_index(op.f("ix_channel_ref_id"), "channel_ref", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_channel_ref_id"), table_name="channel_ref")
    op.drop_table("channel_ref")
    # ### end Alembic commands ###
