"""Initials

Revision ID: cdc9e3b87376
Revises: 
Create Date: 2023-10-05 06:54:43.006530+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# Revision identifiers, used by Alembic
revision: str = "cdc9e3b87376"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_offering_ref",
        sa.Column("referred_type", sa.String(length=255), nullable=False),
    )
    op.drop_column("product_offering_ref", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_offering_ref",
        sa.Column("type", mysql.VARCHAR(length=255), nullable=False),
    )
    op.drop_column("product_offering_ref", "referred_type")
    # ### end Alembic commands ###
