"""Initials

Revision ID: ee9309f94d71
Revises: 
Create Date: 2023-10-04 11:54:48.683348+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# Revision identifiers, used by Alembic
revision: str = "ee9309f94d71"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_offering_ref",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("href", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("referred_type", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_offering_ref_id"), "product_offering_ref", ["id"], unique=False
    )
    op.add_column(
        "related_party_ref",
        sa.Column("referred_type", sa.String(length=255), nullable=True),
    )
    op.alter_column(
        "related_party_ref",
        "href",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "related_party_ref",
        "name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "related_party_ref",
        "role",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_constraint(
        "related_party_ref_ibfk_1", "related_party_ref", type_="foreignkey"
    )
    op.drop_column("related_party_ref", "reservation_id")
    op.add_column(
        "reservation", sa.Column("base_type", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "reservation",
        sa.Column("schema_location", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "reservation", sa.Column("description", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "reservation",
        sa.Column("reservation_state", sa.String(length=255), nullable=True),
    )
    op.alter_column(
        "reservation", "type", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "reservation", "href", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "reservation",
        "valid_for",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_column("reservation", "baseType")
    op.drop_column("reservation", "schemaLocation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservation",
        sa.Column("schemaLocation", mysql.VARCHAR(length=255), nullable=False),
    )
    op.add_column(
        "reservation", sa.Column("baseType", mysql.VARCHAR(length=255), nullable=False)
    )
    op.alter_column(
        "reservation",
        "valid_for",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "reservation", "href", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "reservation", "type", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.drop_column("reservation", "reservation_state")
    op.drop_column("reservation", "description")
    op.drop_column("reservation", "schema_location")
    op.drop_column("reservation", "base_type")
    op.add_column(
        "related_party_ref",
        sa.Column("reservation_id", mysql.VARCHAR(length=255), nullable=False),
    )
    op.create_foreign_key(
        "related_party_ref_ibfk_1",
        "related_party_ref",
        "reservation",
        ["reservation_id"],
        ["id"],
    )
    op.alter_column(
        "related_party_ref",
        "role",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "related_party_ref",
        "name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "related_party_ref",
        "href",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("related_party_ref", "referred_type")
    op.drop_index(op.f("ix_product_offering_ref_id"), table_name="product_offering_ref")
    op.drop_table("product_offering_ref")
    # ### end Alembic commands ###
