"""
Add pool id in vlan table

Revision ID: b4298a12faf9
Revises: 823e6f4f7887
Create Date: 2023-11-26 07:27:34.084127+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic
revision: str = "b4298a12faf9"
down_revision: str | None = "823e6f4f7887"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vlan_allocation",
        sa.Column("resource_pool_id", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vlan_allocation", "resource_pool_id")
    # ### end Alembic commands ###
