"""
Add vlan_allocation table

Revision ID: 823e6f4f7887
Revises: 4805a696deba
Create Date: 2023-11-24 09:28:30.881796+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic
revision: str = "823e6f4f7887"
down_revision: str | None = "4805a696deba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vlan_allocation",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("used_vlan_numbers", sa.ARRAY(sa.Integer()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vlan_allocation_id"), "vlan_allocation", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vlan_allocation_id"), table_name="vlan_allocation")
    op.drop_table("vlan_allocation")
    # ### end Alembic commands ###
