"""
Initials

Revision ID: 63d52cbdb74d
Revises: 
Create Date: 2023-10-10 10:04:21.401769+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic
revision: str = "63d52cbdb74d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservation",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("href", sa.String(length=255), nullable=True),
        sa.Column("base_type", sa.String(length=255), nullable=True),
        sa.Column("schema_location", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("reservation_state", sa.String(length=255), nullable=True),
        sa.Column(
            "valid_for", sa.Date(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reservation_id"), "reservation", ["id"], unique=False)
    op.create_table(
        "channel_ref",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("href", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("referred_type", sa.String(length=255), nullable=False),
        sa.Column("reservation_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_index(op.f("ix_channel_ref_id"), "channel_ref", ["id"], unique=False)
    op.create_table(
        "product_offering_ref",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("href", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("referred_type", sa.String(length=255), nullable=False),
        sa.Column("reservation_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_index(
        op.f("ix_product_offering_ref_id"), "product_offering_ref", ["id"], unique=False
    )
    op.create_table(
        "related_party_ref",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("referred_type", sa.String(length=255), nullable=True),
        sa.Column("href", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column("reservation_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_index(
        op.f("ix_related_party_ref_id"), "related_party_ref", ["id"], unique=False
    )
    op.create_table(
        "requested_period",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("base_type", sa.String(length=255), nullable=False),
        sa.Column("schema_location", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column("days_of_week", sa.String(length=255), nullable=False),
        sa.Column("from_to_date_time", sa.String(length=255), nullable=False),
        sa.Column("range_interval", sa.String(length=255), nullable=False),
        sa.Column(
            "valid_for", sa.Date(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("reservation_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_index(
        op.f("ix_requested_period_id"), "requested_period", ["id"], unique=False
    )
    op.create_table(
        "reservation_item",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("sub_reservation_state", sa.String(length=255), nullable=True),
        sa.Column("applied_capacity_amount", sa.String(length=255), nullable=True),
        sa.Column("base_type", sa.String(length=255), nullable=True),
        sa.Column("schema_location", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("reservation_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_index(
        op.f("ix_reservation_item_id"), "reservation_item", ["id"], unique=False
    )
    op.create_table(
        "resource_capacity_demand",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column(
            "resource_capacity_demand_amount", sa.String(length=255), nullable=False
        ),
        sa.Column("base_type", sa.String(length=255), nullable=False),
        sa.Column("schema_location", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column(
            "applicable_time_period",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "valid_for", sa.Date(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("place", sa.String(length=255), nullable=False),
        sa.Column("pattern", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("reservation_item_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_item_id"],
            ["reservation_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_item_id"),
    )
    op.create_index(
        op.f("ix_resource_capacity_demand_id"),
        "resource_capacity_demand",
        ["id"],
        unique=False,
    )
    op.create_table(
        "resource_pool",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("href", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("related_party", sa.String(length=255), nullable=False),
        sa.Column("resource_collection", sa.String(length=255), nullable=False),
        sa.Column("base_type", sa.String(length=255), nullable=False),
        sa.Column("schema_location", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column("resource_capacity_demand_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_capacity_demand_id"],
            ["resource_capacity_demand.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_capacity_demand_id"),
    )
    op.create_index(op.f("ix_resource_pool_id"), "resource_pool", ["id"], unique=False)
    op.create_table(
        "resource_ref",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("object_id", sa.String(length=255), nullable=False),
        sa.Column("href", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("resource_pool_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_pool_id"],
            ["resource_pool.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_pool_id"),
    )
    op.create_index(op.f("ix_resource_ref_id"), "resource_ref", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resource_ref_id"), table_name="resource_ref")
    op.drop_table("resource_ref")
    op.drop_index(op.f("ix_resource_pool_id"), table_name="resource_pool")
    op.drop_table("resource_pool")
    op.drop_index(
        op.f("ix_resource_capacity_demand_id"), table_name="resource_capacity_demand"
    )
    op.drop_table("resource_capacity_demand")
    op.drop_index(op.f("ix_reservation_item_id"), table_name="reservation_item")
    op.drop_table("reservation_item")
    op.drop_index(op.f("ix_requested_period_id"), table_name="requested_period")
    op.drop_table("requested_period")
    op.drop_index(op.f("ix_related_party_ref_id"), table_name="related_party_ref")
    op.drop_table("related_party_ref")
    op.drop_index(op.f("ix_product_offering_ref_id"), table_name="product_offering_ref")
    op.drop_table("product_offering_ref")
    op.drop_index(op.f("ix_channel_ref_id"), table_name="channel_ref")
    op.drop_table("channel_ref")
    op.drop_index(op.f("ix_reservation_id"), table_name="reservation")
    op.drop_table("reservation")
    # ### end Alembic commands ###
