"""
foreign key constrain applied to resource pool 

Revision ID: aac30906a30e
Revises: d3cc1dbb8015
Create Date: 2023-10-09 15:20:24.923367+00:00
"""
from collections.abc import Sequence

from alembic import op

# Revision identifiers, used by Alembic
revision: str = "aac30906a30e"
down_revision: str | None = "d3cc1dbb8015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("resource_pool_ibfk_1", "resource_pool", type_="foreignkey")
    op.create_foreign_key(
        None, "resource_pool", "resource_capacity_demand", ["resource_pool_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "resource_pool", type_="foreignkey")
    op.create_foreign_key(
        "resource_pool_ibfk_1",
        "resource_pool",
        "resource_pool",
        ["resource_pool_id"],
        ["id"],
    )
    # ### end Alembic commands ###
