"""
resource capacity demand table added

Revision ID: 071670c52022
Revises: d9f0c8620990
Create Date: 2023-10-09 04:54:23.436113+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic
revision: str = "071670c52022"
down_revision: str | None = "d9f0c8620990"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_capacity_demand",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column(
            "resource_capacity_demand_amount", sa.String(length=255), nullable=False
        ),
        sa.Column("base_type", sa.String(length=255), nullable=False),
        sa.Column("schema_location", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column(
            "applicable_time_period",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "valid_for", sa.Date(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("place", sa.String(length=255), nullable=False),
        sa.Column("pattern", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("reservation_item_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_item_id"],
            ["reservation_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_item_id"),
    )
    op.create_index(
        op.f("ix_resource_capacity_demand_id"),
        "resource_capacity_demand",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_resource_capacity_demand_id"), table_name="resource_capacity_demand"
    )
    op.drop_table("resource_capacity_demand")
    # ### end Alembic commands ###
